In [1]:
!pip install numpy

In [2]:
import numpy as np
#creat
data=np.random.rand(2,3,4)
zeros=np.zeros((2,2,2))
full7=np.full((2,2,2),7)
ones=np.ones((2,2,2))
arr=np.array([[1,2,3],[1,2,3]])
print(type(arr))


<class 'numpy.ndarray'>


In [3]:
#attributes
shape=data.shape
size=data.size
typed=data.dtype

In [4]:
#slicing
arr=data[0]
slicer=data[0:2]
last=data[-1]
singleval=data[0][0][0]

In [12]:
# basic math
list1=np.random.rand(10)
list2=np.random.rand(10)
add=np.add(list1,list2)
sub=np.subtract(list1,list2)
div=np.divide(list1,list2)
mul=np.multiply(list1,list2)
dot_product=np.dot(list1,list2)

In [28]:
#stat function
sqrt=np.sqrt(25)
abs=np.abs(-2)
power=np.power(2,5)
log=np.log(32)#in base e
log2=np.log2(32)
exp=np.exp([1,2])
min=np.min(list1)
max=np.max(list2)


In [61]:
#reshape data
data=data.reshape((2,2,-1))
# append 
zeros=np.zeros((5))
print(zeros)
zeros=np.append(zeros,[4,5])
print(zeros)
#insert to array in a location
zeros=np.insert(zeros,[2,6],[1,10]) # sync , 10 lacate in 7-th index
print(zeros)
zeros=np.insert(zeros,5,11)
print(zeros)
zeros[[2,4]]=[8,9]
print(zeros)

[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 4. 5.]
[ 0.  0.  1.  0.  0.  0.  4. 10.  5.]
[ 0.  0.  1.  0.  0. 11.  0.  4. 10.  5.]
[ 0.  0.  8.  0.  9. 11.  0.  4. 10.  5.]


In [78]:
#delete
data=np.random.rand(2,3,4)
data=data.reshape((2,2,-1))
print(data)
data=np.delete(data,0,axis=1)#delete 0-th array from axis
print(data)

[[[0.46836196 0.3300794  0.14144797 0.38704462 0.46682932 0.24052784]
  [0.19794288 0.23750402 0.96728488 0.38110006 0.63545763 0.76962277]]

 [[0.91496389 0.32511366 0.67194637 0.89996623 0.01708722 0.85867074]
  [0.35998368 0.01784695 0.35900197 0.52762174 0.21731021 0.77406073]]]


In [79]:
#save and load 
np.save('new array',data)
newarray=np.load('new array.npy')
